### ISSUE TITLE
Different resolutions for global and local crops

### ISSUE THREAD

**Issue by vadimkantorov** [facebookresearch/dino#15]
Hi @mathildecaron31! Thanks for the great package and concise codebase :)

The global crops haver resolution `224 x 224` and local are `96 x 96`: https://github.com/facebookresearch/dino/blob/58aabc09e056689228e5cfff27c2c20e6d19c945/main_dino.py#L436.

Was it important that the local ones are kept `96 x 96`?

I'm building an extension and the code of course becomes simpler if all views are `224 x 224` (since you can collate everything together and need not separate forward passes per resolution), but I wonder if you thing that it would impact the accuracy (besides slowed computation time).

Thanks!

**Comment by mathildecaron31** [comment]
Hi @vadimkantorov, thanks for your interest in this work :).
In order to have only `224x224` crops, I see three options:

1- Pad the `96x96` crops to `224x224` resolution. It will increase the memory usage a lot but this will give you exactly the same performance while using only one forward. This will require you a bit of coding but I can definitely help since I have already implemented that in my experiments. For padding I took inspiration from [DETR](https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/util/misc.py#L283-L328) excellent codebase. For padding in the attentions I added after https://github.com/facebookresearch/dino/blob/534f37f000a10afff97c0d96ec4df81875193699/vision_transformer.py#L73
```
if mask is not None:
    mask = (mask==1).unsqueeze(1).unsqueeze(2).repeat(1, 6, 197, 1)
    attn = attn.masked_fill(mask, -1e4)
```

2- Try increasing the resolution of the local crops to `224x224`. I expect a performance drop but it is possible that with further experimentations and tuning of multi-crop parameters, you can recover this drop.

3- Training without multi-crop (i.e. only 2 224x224 crops). In this case, a drop of performance is expected. To disable multi-crop you should set `--local_crops_number 0` and adapt the scaling of the global crops accordingly: `--global_crops_scale 0.14 1`.

**Comment by mathildecaron31** [comment]
I am closing the issue. Feel free to reopen if you need further assistance.
