### ISSUE TITLE
Parallelize multiple crops

### ISSUE THREAD

**Issue by 4knahs** [facebookresearch/dino#154]
Hi,

Atm the student multi-crop wrapper is [running different crops sequentially](https://github.com/facebookresearch/dino/blob/cb711401860da580817918b9167ed73e3eef3dcf/utils.py#L620), these could potentially run in parallel in the GPU if they were passed as a single batch to the student network.

Any particular reason why these were kept sequential? I.e., is there any performance requirement on performing two backward propagations (one for each crop/augmentation) ? 

Thanks

**Comment by mathildecaron31** [comment]
Hi @4knahs 

Thanks for your interest. Crops with the same resolution are batched together so that there is one forward per resolution. We perform forward pass separately on each resolution input. The inputs corresponding to a single resolution are clubbed and single forward is run on the same resolution inputs. Hence we do several forward passes = number of different resolutions used. 

We cannot batch crops of different resolution though.

Hope that helps.
