### ISSUE TITLE
Questions about the Relation to SwAV

### ISSUE THREAD

**Issue by shallowtoil** [facebookresearch/dino#49]
Hi, @mathildecaron31. I have a question about a detail in the paper. In Appendix B, Relation to SwAV (Table 14), the paper did an ablative study in terms of composing parts in terms of Momentum encoder and Extra operation. I'm wondering Whether softmax over channel dimension is appended for experiment except Centering (i.e., experiment 2,3,5,6). Since DINO uses an extra channel-wise softmax after Centering to compute the loss, while in SwAV, outputs after batch-level softmax/SK algorithm are used to compute CE.

**Comment by mathildecaron31** [comment]
Hi @shallowtoil ,

We do not append softmax over channel dimension for experiments 2,3,5,6 since the normalization in the channel dimension is done by others means (SK or simple normalization). We perform exactly the operation which are described in the corresponding code snippets in the following paragraph "Details on the Softmax(batch) variant.". It is true that better clarity, we could replace the term `centering` in rows 1 and 2 by `centering + softmax(channel)`.

Hope that helps, feel free to ask further questions if that it is still not clear.

**Comment by shallowtoil** [comment]
Thanks for the reply!
